config/routes.rb
Rails.application.routes.draw do
   # Defines the root path route ("/")
   root "boards#new"
   
  resources :boards
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :width, presence: true, numericality: { greater_than: 0 }
  validates :height, presence: true, numericality: { greater_than: 0 }
  validates :mine_count, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: :area}

  def area 
    return self.width * self.height
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
    @recent_boards = Board.all.order(created_at: :desc).limit(10)
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @recent_boards = Board.all.order(created_at: :desc).limit(10)
    @board = Board.new(board_params)
    respond_to do |format|      
      if @board.save
        build_grid(@board)
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        build_grid(@board)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:name, :email, :width, :height, :grid, :mine_count)
    end

    def build_grid(board)
      board.grid = Array.new(board.height){ Array.new(board.width) }
      mines = []
      random_possibilities = (0...board.area).to_a.shuffle
      board.mine_count.times do 
        mines.push(random_possibilities.pop)
      end
      mines.each do |mine| 
        cordinates = mine.divmod(board.width)
        x = cordinates[0]
        y = cordinates[1]
        board.grid[x][y] = true
      end 
      board.save
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>" class="row board-row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <strong>Name:</strong> <%= board.name %>
      </div>    
      <div class="card-body">
        <p>
          <strong>Email:</strong>
          <%= board.email %>
        </p>
        <p>
          <strong>Board:</strong>
          <%= board.width %> X <%= board.height %> (<%= board.width * board.height %> squares) -  💣<%= board.mine_count %>
        </p>
        <div style="display:flex;flex-direction:column">
          <% board.grid.each do |row| %>
            <div>
              <% row.each do |col| %>
                <% if col == nil %>
                  <input type="checkbox" disabled style="width:16px">
                <% end %>
                <% if col == true %>
                  <span>💣</span>
                <% end %>          
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :name, style: "display: block", class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :email, style: "display: block", class: "form-label" %>
        <%= form.text_field :email, class: "form-control" %>
        <div class="form-text">we will never share your email</div>
      </div>
      <div class="row">
        <div class="col">
          <div class="mb-3">
            <%= form.label :width, style: "display: block", class: "form-label" %>
            <%= form.number_field :width, class: "form-control" %>
          </div>
        </div>
        <div class="col">
          <div class="mb-3">
            <%= form.label :height, style: "display: block", class: "form-label" %>
            <%= form.number_field :height, class: "form-control" %>
          </div>
        </div>
        <div class="col">
          <div class="mb-3">
            <%= form.label :mine_count, style: "display: block", class: "form-label" %>
            <%= form.number_field :mine_count, class: "form-control" %>
          </div>
        </div>        
      </div>
      <div class="mb-3 text-right">
        <%= form.submit "Generate Board", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  
</form>


<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row pt-3 pb-5">
  <div class="col">
    <h1 class="text-center">Boards</h1>
  </div>
</div>

<div class="row pt-1 pb-4">
  <div class="col">
    <%= link_to "New board", new_board_path, class: "btn btn-success float-end" %>
  </div>
</div>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <div class="row pt-1 pb-4">
      <div class="col">
        <%= link_to "Show this board", board, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="row justify-content-center pt-5">
  <div class="col-6 ">
    <h1 class="text-center pb-3">New board</h1>
    <%= render "form", board: @board %>
  </div>
</div>
<div class="row justify-content-center pt-5">
  <div class="col-9 ">
    <h1 class="text-center pb-3">10 Most Recent Boards </h1>
    <table class="table table-dark table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Grid</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
        <% @recent_boards.each do |board| %>
        <tr>
          <td><%= board.id %></td>
          <td>
            <%= link_to board.name, board, style: "color:white;" %>
          </td>
          <td><%= board.email %></td>
          <td>
            <%=board.width%> X <%=board.height %> (<%= board.width * board.height %>) -  💣 <%= board.mine_count %>
          <td>
            <%= board.created_at.strftime("%m/%d/%Y")%><br/>
            <small><%= time_ago_in_words(board.created_at) %></small>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row pt-5 pb-4 text-center">
  <div class="col">
    <%= link_to "View All Generated Boards", boards_path, class: "btn btn-primary" %> 
  </div>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board  %>

<div class="row pt-4 pb-5">
  <div class="col">
  <%= link_to "Edit this board", edit_board_path(@board), class: "btn btn-primary" %> 
  <%= link_to "View All Generated Boards", boards_path, class: "btn btn-primary" %>
  <%= button_to "Destroy this board", @board, method: :delete, class: "btn btn-danger", form_class: "delete-board-form" %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<div id="hello-component"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onestep Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background-color:#FBFBFB;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <%= image_tag "mine_logo.png", width:30, alt:"minesweeper logo" %>          
          Onestep Minesweeper
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mb-2 mb-lg-0 me-auto">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>  
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>